bigemoji/slackapp/urls.py
from django.urls import path

from . import views


app_name = "slackapp"
urlpatterns = [path("", views.index, name="index")]

bigemoji/urls.py
from django.urls import path, include
from . import views


app_name = 'bigemoji'
urlpatterns = [
    path('', views.index, name='index'),
    path('bigemoji/<team_id>/<slack_user_id>/', include([
        path('', views.bigemoji_index, name='bigemoji'),
        path('add/', views.bigemoji_add, {'is_alias': False}, name='add'),
        path('alias/', views.bigemoji_add, {'is_alias': True}, name='alias'),
        path('remove/<bigemoji_name>', views.bigemoji_remove, name='remove'),
    ])),
    path('app/', include('bigemoji.slackapp.urls'))
]

chatbot/urls.py
from django.urls import path
from . import views


app_name = 'chatbot'
urlpatterns = [
    path('slack/', views.slack_index, name='slack_index')
]

bigemoji/models.py
import datetime

from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils import timezone

from slackauth.models import SlackTeam, SlackAccount


def team_directory(instance, filename):
    return '{}/{}_{}'.format(instance.team.id,
                             instance.emoji_name,
                             filename)


class BigEmojiFullException(Exception):
    pass


class BigEmojiStorage(models.Model):
    team = models.OneToOneField(SlackTeam, on_delete=models.CASCADE)
    occupied = models.IntegerField(default=0)
    max_size = models.IntegerField(default=10000000)
    entries = models.IntegerField(default=0)
    max_entry = models.IntegerField(default=1000)
    delete_eta = models.IntegerField(default=3600)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='date created')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='date updated')

    def __str__(self):
        return self.team.__str__()


class BigEmoji(models.Model):
    owner = models.ForeignKey(SlackAccount, on_delete=models.CASCADE)
    storage = models.ForeignKey(BigEmojiStorage, on_delete=models.CASCADE)
    emoji_name = models.CharField(max_length=100)
    image_file = models.ImageField(upload_to=team_directory, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='date created')
    alias = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('storage', 'emoji_name'),)

    def __str__(self):
        return self.emoji_name

    @property
    def team(self):
        return self.storage.team

    @property
    def is_alias(self):
        return self.alias is not None

    def clean(self):
        if self.image_file is None and self.alias is None:
            raise ValidationError('The BigEmoji should contain an image or should be an alias.')

        if self.alias is not None and self.alias.alias is not None:
            raise ValidationError('Cannot alias an alias.')

    @property
    def image(self):
        if self.alias is not None:
            return self.alias.image_file
        else:
            return self.image_file

    @property
    def size(self):
        if self.alias is not None:
            return 0
        else:
            return self.image_file.size

    @transaction.atomic
    def save_emoji(self):
        storage = BigEmojiStorage.objects.select_for_update().get(pk=self.storage_id)
        if storage.entries < storage.max_entry:
            if self.alias is not None or storage.occupied + self.image_file.size < storage.max_size:
                self.save()
                if not self.is_alias:
                    storage.occupied += self.image_file.size
                storage.entries += 1
                storage.save()
            else:
                raise BigEmojiFullException()
        else:
            raise BigEmojiFullException()

    @transaction.atomic
    def delete_emoji(self):
        storage = BigEmojiStorage.objects.select_for_update().get(pk=self.storage_id)
        if not self.is_alias:
            storage.occupied -= self.image_file.size
        storage.entries -= 1
        storage.save()
        self.delete()

    def was_created_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_created <= now
    was_created_recently.admin_order_field = 'date_created'
    was_created_recently.boolean = True
    was_created_recently.short_description = 'Created recently?'


@receiver(post_delete, sender=BigEmoji)
def remove_file_on_delete(sender, instance, **kwargs):
    if instance.image_file:
        instance.image_file.delete(save=False)

bigemoji/forms.py
from django import forms

from .models import BigEmoji


class BigEmojiForm(forms.ModelForm):
    class Meta:
        model = BigEmoji
        fields = ['emoji_name', 'image_file']


class BigEmojiAliasForm(forms.ModelForm):
    class Meta:
        model = BigEmoji
        fields = ['emoji_name', 'alias']

    def __init__(self, storage, *args, **kwargs):
        super(BigEmojiAliasForm, self).__init__(*args, **kwargs)
        if storage is None:
            self.fields['alias'].queryset = BigEmoji.objects.none()
        else:
            self.fields['alias'].queryset = BigEmoji.objects.filter(storage=storage, alias__isnull=True)

bigemoji/slackapp/views.py
from django.views.decorators.http import require_POST
from django.conf import settings
from django.http import JsonResponse, HttpResponse

import shlex

from slackauth.decorators import slack_request
from .tasks import upload_bigemoji, bigemoji_list


@require_POST
@slack_request
def index(request):
    cmd = request.POST.get('command')
    cmd_args = shlex.split(request.POST.get('text'))
    slack_user_id = request.POST.get('user_id')
    team_id = request.POST.get('team_id')
    channel_id = request.POST.get('channel_id')
    response_url = request.POST.get('response_url')

    commands = settings.BIGEMOJI_SLACKAPP_COMMANDS
    if cmd in commands.get('bigemoji'):
        if len(cmd_args) == 1:
            bigemoji_name = cmd_args[0]
            upload_bigemoji.delay(team_id, channel_id, slack_user_id, bigemoji_name, response_url)
            return HttpResponse()
        else:
            return JsonResponse({
                'response_type': 'ephemeral',
                'text': 'The command should contain exactly 1 argument.'
            })
    elif cmd in commands.get('bigemoji_list'):
        bigemoji_list.delay(team_id, response_url)
        return HttpResponse()
    else:
        return JsonResponse({
            'response_type': 'ephemeral',
            'text': 'Unknown command!'
        })

bigemoji/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from django.views.decorators.http import require_POST

from .forms import BigEmojiForm, BigEmojiAliasForm
from .models import BigEmoji, BigEmojiStorage, BigEmojiFullException
from slackauth.decorators import slack_login_required
from slackauth.models import SlackAccount, SlackTeam


@login_required
def index(request):
    try:
        request_uid = request.GET.get('uid', '_')
        team_id, slack_user_id = request_uid.split('_')
        account_set = SlackAccount.objects.filter(account__user=request.user)
        try:
            team = SlackTeam.objects.get(pk=team_id)
            account = account_set.get(team=team, slack_user_id=slack_user_id)
        except (SlackTeam.DoesNotExist, SlackAccount.DoesNotExist):
            account = account_set[0:1].get()

        team_id, slack_user_id = account.team.id, account.slack_user_id
        return HttpResponseRedirect(reverse('bigemoji:bigemoji', args=(team_id, slack_user_id)))

    except (SlackTeam.DoesNotExist, SlackAccount.DoesNotExist, ValueError):
        return HttpResponseNotFound()


@slack_login_required
def bigemoji_index(request, account, account_set):
    try:
        team = account.team
        if team.verified:
            storage, _ = BigEmojiStorage.objects.get_or_create(defaults={
                'max_size': settings.BIGEMOJI_MAX_SPACE,
                'max_entry': settings.BIGEMOJI_MAX_ENTRY,
                'delete_eta': settings.BIGEMOJI_DELETE_ETA,
            }, team=team)
            empty_add_form = BigEmojiForm()
            empty_alias_form = BigEmojiAliasForm(storage)
            bigemojis = BigEmoji.objects.filter(storage=storage).order_by('-date_created')
        else:
            empty_add_form = BigEmojiForm()
            empty_alias_form = BigEmojiAliasForm(None)
            bigemojis = BigEmoji.objects.none()

        return render(request, 'bigemoji/index.html', {
            'add_form': empty_add_form,
            'alias_form': empty_alias_form,
            'account_set': account_set,
            'account_user': account,
            'team_id': team.id,
            'bigemojis': bigemojis,
        })

    except ValueError:
        return HttpResponseNotFound()


@require_POST
@slack_login_required
def bigemoji_add(request, account, account_set, is_alias):
    try:
        team = account.team

        if team.verified:
            storage = team.bigemojistorage
            bigemoji = BigEmoji(owner=account, storage=storage)
            if is_alias:
                bigemoji = BigEmojiAliasForm(storage, request.POST, instance=bigemoji).save(commit=False)
            else:
                bigemoji = BigEmojiForm(request.POST, request.FILES, instance=bigemoji).save(commit=False)

            try:
                bigemoji.save_emoji()
            except IntegrityError:
                # Django seems to raise an error after it saves the file.
                bigemoji.image_file.delete(save=False)
                messages.add_message(
                    request,
                    messages.ERROR,
                    'A BigEmoji with that name already exists.'
                )
            except BigEmojiFullException:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Your workspace\'s BigEmoji storage is full. Please contact the administrators.'
                )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Your workspace is not allowed to use this app. Please contact the administrators.'
            )

        return HttpResponseRedirect(reverse('bigemoji:bigemoji', args=(team.id, account.slack_user_id)))
    except (BigEmojiStorage.DoesNotExist, ValueError) as e:
        print(e)
        return HttpResponseNotFound()


@require_POST
@slack_login_required
def bigemoji_remove(request, account, account_set, bigemoji_name):
    try:
        team = account.team
        storage = team.bigemojistorage
        bigemoji = BigEmoji.objects.get(storage=storage, emoji_name=bigemoji_name)
        if bigemoji.owner == account:
            bigemoji.delete_emoji()
            messages.add_message(
                request,
                messages.INFO,
                'Successfully deleted BigEmoji {} and its aliases.'.format(bigemoji_name)
            )
            return HttpResponseRedirect(reverse('bigemoji:bigemoji', args=(team.id, account.slack_user_id)))
        else:
            return HttpResponseNotFound()
    except (BigEmojiStorage.DoesNotExist, BigEmoji.DoesNotExist):
        return HttpResponseNotFound()

bigemoji/templates/bigemoji/index.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Big Emoji" %}{% endblock %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'style/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bigemoji/style.css' %}">
{% endblock %}

{% block content %}

{% url 'bigemoji:index' as default_url %}

<header>
    <span class="logo">JJAL BOT</span>
    <div class="menu">
        <ul>
            <li>
                <button class="top-button">
                    <a class="top-button" href="{% url 'account_logout' %}">Sign Out</a>
                </button>
            </li>
            <li>
                <button class="top-button">
                    <a class="top-button" href="{% provider_login_url "slack" process="connect" next=default_url scope=slack_login_scope %}">
                        Sign in to another workspace
                    </a>
                </button>
            </li>
        </ul>
    </div>
</header>

{% if error_msg %}
    <p><strong>{{ error_msg }}</strong></p>
{% endif %}

<form action="{{ default_url }}" method="get">
    <select name="uid">
    {% for account in account_set %}
        {% if account == account_user %}
        <option value="{{ account.team.id }}_{{ account.slack_user_id }}" selected>{{ account.team.domain }} - {{ account.account.user.username }}</option>
        {% else %}
        <option value="{{ account.team.id }}_{{ account.slack_user_id }}">{{ account.team.domain }} - {{ account.account.user.username }}</option>
        {% endif %}
    {% endfor %}
    </select>
    <input class="button" type="submit" value="Change account" />
</form>

<p>
    To use Slack slash command,
    <a href="{% provider_login_url "slack" process="redirect" next=default_url scope="files:write:user,chat:write:user" auth_params="team="|add:team_id %}">
        please grant us file upload and chat update permissions.
    </a>
</p>
<div class="inline">{% blocktrans %}Not installed in your workspace? Consider {% endblocktrans %}</div>

<div class="add-to-slack">
    <a class="add-to-slack" href="{% provider_login_url "slack" process="redirect" next=default_url scope="bot,commands" auth_params="team="|add:team_id %}">
        <img alt="Add to Slack" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" />
    </a>
</div>

<form action="{% url 'bigemoji:add' team_id=account_user.team.id slack_user_id=account_user.slack_user_id %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ add_form }}
    <input class="button" type="submit" value="Submit" />
</form>

<form action="{% url 'bigemoji:alias' team_id=account_user.team.id slack_user_id=account_user.slack_user_id %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ alias_form }}
    <input class="button" type="submit" value="Submit" />
</form>

<br />

<table>
    <tr>
        <th>Owner</th>
        <th>Name</th>
        <th>Big Emoji</th>
        <th>Delete</th>
    </tr>
{% for bigemoji in bigemojis %}
    <tr>
        <td>{{ bigemoji.owner }}</td>
        <td>{{ bigemoji.emoji_name }}</td>
        <td><img class="bigemoji" src="{{ bigemoji.image.url }}" /></td>
        <td>
            {% if bigemoji.owner == account_user %}
            <form action="{% url 'bigemoji:remove' team_id=account_user.team.id slack_user_id=account_user.slack_user_id bigemoji_name=bigemoji.emoji_name %}" method="post">
                {% csrf_token %}
                <input class="delete-button" type="submit" value="Delete" />
            </form>
            {% endif %}
        </td>
    </tr>
{% endfor %}
</table>

{% endblock %}